window.clientTemplates = {
    question1_28_03_25: 'https://assets.internal.inthegame.io/templates/azteka/question1_28_03_25.json',
    question2_28_03_25: 'https://assets.internal.inthegame.io/templates/azteka/question2_28_03_25.json',
    question3_28_03_25: 'https://assets.internal.inthegame.io/templates/azteka/question3_28_03_25.json',
    question4_28_03_25: 'https://assets.internal.inthegame.io/templates/azteka/question4_28_03_25.json',
    unique_feedback_28_03_25: 'https://assets.internal.inthegame.io/templates/azteka/unique_feedback_28_03_25.json',
    correct_feedback_28_03_25: 'https://assets.internal.inthegame.io/templates/azteka/correct_feedback_28_03_25.json',
    incorrect_feedback_28_03_25: 'https://assets.internal.inthegame.io/templates/azteka/incorrect_feedback_28_03_25.json',
    lband_test: 'https://assets.internal.inthegame.io/templates/azteka/lband_test.json',
    sidebar_video: 'https://assets.internal.inthegame.io/templates/azteka/sidebar_video_azteka.json',
    lband: 'https://assets.internal.inthegame.io/templates/azteka/lband_azteka.json',
    splitscreen: 'https://assets.internal.inthegame.io/templates/azteka/splitscreen_azteka.json',
    quiz_web: 'https://assets.internal.inthegame.io/templates/azteka/azteka_quiz_web.json',
    quiz_web_correct: 'https://assets.internal.inthegame.io/templates/azteka/azteka_quiz_web_correct.json',
    quiz_web_incorrect: 'https://assets.internal.inthegame.io/templates/azteka/azteka_quiz_web_incorrect.json',
    quiz_web_Question_answers: 'https://assets.internal.inthegame.io/templates/azteka/azteka_quiz_web_Q&A.json',
    quiz_web_correct_team_odds: 'https://assets.internal.inthegame.io/templates/azteka/azteka_demo_correct_web_team&odds.json',
    quiz_web_incorrect_team_odds: 'https://assets.internal.inthegame.io/templates/azteka/azteka_demo_incorrect__web_team&odds.json',
}; 